AWSTemplateFormatVersion: "2010-09-09"
Description: >
  CloudFormation template for Plantopedia, a highly available web application
  providing a plant encyclopedia. This template provisions a custom VPC across
  multiple Availability Zones and an Amazon RDS PostgreSQL instance with Multi-AZ
  failover, with credentials stored in AWS Secrets Manager.

Parameters:
  VpcCidr:
    Type: String
    Description: "CIDR block for the Plantopedia VPC"
    Default: "10.0.0.0/16"
  PublicSubnet1Cidr:
    Type: String
    Description: "CIDR block for Plantopedia Public Subnet 1"
    Default: "10.0.1.0/24"
  PublicSubnet2Cidr:
    Type: String
    Description: "CIDR block for Plantopedia Public Subnet 2"
    Default: "10.0.2.0/24"
  PrivateSubnet1Cidr:
    Type: String
    Description: "CIDR block for Plantopedia Private Subnet 1"
    Default: "10.0.3.0/24"
  PrivateSubnet2Cidr:
    Type: String
    Description: "CIDR block for Plantopedia Private Subnet 2"
    Default: "10.0.4.0/24"
  PlantopediaDBUser:
    Type: String
    Description: "The Plantopedia RDS database username"
    Default: "plantuser"
  PlantopediaDBPassword:
    Type: String
    NoEcho: true
    Description: "The Plantopedia RDS database password"
  PlantopediaDBName:
    Type: String
    Description: "The name of the Plantopedia RDS database"
    Default: "plantopedia"
  PlantopediaDBAllocatedStorage:
    Type: Number
    Description: "Allocated storage for the Plantopedia RDS DB instance (in GB)"
    Default: 20
  PlantopediaDBInstanceClass:
    Type: String
    Description: "Plantopedia RDS DB instance class"
    Default: "db.t3.medium"

Resources:
  # VPC and Networking Resources
  PlantopediaVPC9:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: "PlantopediaVPC9"

  PlantopediaInternetGateway9:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: "PlantopediaIGW9"

  PlantopediaVPCGatewayAttachment9:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref PlantopediaVPC9
      InternetGatewayId: !Ref PlantopediaInternetGateway9

  PlantopediaPublicSubnet19:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref PlantopediaVPC9
      CidrBlock: !Ref PublicSubnet1Cidr
      AvailabilityZone: !Select [0, !GetAZs ""]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: "PlantopediaPublicSubnet19"

  PlantopediaPublicSubnet29:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref PlantopediaVPC9
      CidrBlock: !Ref PublicSubnet2Cidr
      AvailabilityZone: !Select [1, !GetAZs ""]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: "PlantopediaPublicSubnet29"

  PlantopediaPrivateSubnet19:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref PlantopediaVPC9
      CidrBlock: !Ref PrivateSubnet1Cidr
      AvailabilityZone: !Select [0, !GetAZs ""]
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: "PlantopediaPrivateSubnet19"

  PlantopediaPrivateSubnet29:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref PlantopediaVPC9
      CidrBlock: !Ref PrivateSubnet2Cidr
      AvailabilityZone: !Select [1, !GetAZs ""]
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: "PlantopediaPrivateSubnet29"

  PlantopediaNATGatewayEIP9:
    Type: AWS::EC2::EIP
    DependsOn: PlantopediaVPCGatewayAttachment9
    Properties:
      Domain: vpc

  PlantopediaNATGateway9:
    Type: AWS::EC2::NatGateway
    DependsOn: PlantopediaVPCGatewayAttachment9
    Properties:
      AllocationId: !GetAtt PlantopediaNATGatewayEIP9.AllocationId
      SubnetId: !Ref PlantopediaPublicSubnet19
      Tags:
        - Key: Name
          Value: "PlantopediaNATGateway9"

  PlantopediaPublicRouteTable9:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref PlantopediaVPC9
      Tags:
        - Key: Name
          Value: "PlantopediaPublicRouteTable9"

  PlantopediaPublicRoute9:
    Type: AWS::EC2::Route
    DependsOn: PlantopediaVPCGatewayAttachment9
    Properties:
      RouteTableId: !Ref PlantopediaPublicRouteTable9
      DestinationCidrBlock: "0.0.0.0/0"
      GatewayId: !Ref PlantopediaInternetGateway9

  PlantopediaPublicSubnet1RouteTableAssociation9:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PlantopediaPublicSubnet19
      RouteTableId: !Ref PlantopediaPublicRouteTable9

  PlantopediaPublicSubnet2RouteTableAssociation9:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PlantopediaPublicSubnet29
      RouteTableId: !Ref PlantopediaPublicRouteTable9

  PlantopediaPrivateRouteTable9:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref PlantopediaVPC9
      Tags:
        - Key: Name
          Value: "PlantopediaPrivateRouteTable9"

  PlantopediaPrivateRoute9:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PlantopediaPrivateRouteTable9
      DestinationCidrBlock: "0.0.0.0/0"
      NatGatewayId: !Ref PlantopediaNATGateway9

  PlantopediaPrivateSubnet1RouteTableAssociation9:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PlantopediaPrivateSubnet19
      RouteTableId: !Ref PlantopediaPrivateRouteTable9

  PlantopediaPrivateSubnet2RouteTableAssociation9:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PlantopediaPrivateSubnet29
      RouteTableId: !Ref PlantopediaPrivateRouteTable9

  # RDS and Secrets Manager Resources
  PlantopediaDBSubnetGroup9:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "Subnet group for Plantopedia RDS instance"
      SubnetIds:
        - !Ref PlantopediaPrivateSubnet19
        - !Ref PlantopediaPrivateSubnet29
      Tags:
        - Key: Name
          Value: "PlantopediaDBSubnetGroup9"

  PlantopediaRDSSecurityGroup9:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Security Group for Plantopedia RDS PostgreSQL instance"
      VpcId: !Ref PlantopediaVPC9
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: !Ref VpcCidr
      Tags:
        - Key: Name
          Value: "PlantopediaRDSSecurityGroup9"

  PlantopediaDBCredentialsSecret9:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: "PlantopediaDBCredentials9"
      Description: "Database credentials for the Plantopedia RDS PostgreSQL instance"
      SecretString: !Sub |
        {
          "username": "${PlantopediaDBUser}",
          "password": "${PlantopediaDBPassword}",
          "dbname": "${PlantopediaDBName}"
        }
      Tags:
        - Key: Environment
          Value: Production

  PlantopediaDBInstance9:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: postgres
      DBInstanceClass: !Ref PlantopediaDBInstanceClass
      AllocatedStorage: !Ref PlantopediaDBAllocatedStorage
      MultiAZ: true
      PubliclyAccessible: false
      VPCSecurityGroups:
        - !Ref PlantopediaRDSSecurityGroup9
      DBSubnetGroupName: !Ref PlantopediaDBSubnetGroup9
      MasterUsername: "{{resolve:secretsmanager:PlantopediaDBCredentials9:SecretString:username}}"
      MasterUserPassword: "{{resolve:secretsmanager:PlantopediaDBCredentials9:SecretString:password}}"
      DBName: !Ref PlantopediaDBName
      BackupRetentionPeriod: 7
      StorageEncrypted: true

Outputs:
  PlantopediaVPCId9:
    Description: "The Plantopedia VPC ID"
    Value: !Ref PlantopediaVPC9
  PlantopediaRDSInstanceEndpoint9:
    Description: "Plantopedia RDS Endpoint"
    Value: !GetAtt PlantopediaDBInstance9.Endpoint.Address
